name = "Tazama"
license = "Apache"
licenselink = "https://github.com/tazama-lf/blob/master/LICENSE"
description = "website"
homepage = "https://tazama.org/"
demosite = "https://tazama.org/"
tags = ["transaction monitoring", "fraud"]
min_version = "0.20"

[author]
  name = "Tazama"
  homepage = "https://tazama.org/"
